##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Wed May 7 11:23:24 2014
##  Generated by MIG Version 2.0
##  
##################################################################################################
##  File name :       DDR3SDRAM.xdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX485T-FFG1761
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         800 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT8JTF12864HZ-1G6
## Data Width: 64
## Time Period: 1250
## Data Mask: 1
##################################################################################################

create_clock -period 5.000 -name sys_clk [get_ports sys_clk_p]
#set_propagated_clock sys_clk_p

############## NET - IOSTANDARD ##################


# PadFunction: IO_L23N_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[0]}]

# PadFunction: IO_L22P_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[1]}]

# PadFunction: IO_L20N_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[2]}]

# PadFunction: IO_L20P_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[3]}]

# PadFunction: IO_L24P_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[4]}]

# PadFunction: IO_L23P_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[5]}]

# PadFunction: IO_L24N_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[6]}]

# PadFunction: IO_L19P_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[7]}]

# PadFunction: IO_L17P_T2_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[8]}]

# PadFunction: IO_L17N_T2_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[9]}]

# PadFunction: IO_L14N_T2_SRCC_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[10]}]

# PadFunction: IO_L14P_T2_SRCC_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[11]}]

# PadFunction: IO_L18P_T2_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[12]}]

# PadFunction: IO_L18N_T2_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[13]}]

# PadFunction: IO_L13N_T2_MRCC_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[14]}]

# PadFunction: IO_L16N_T2_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[15]}]

# PadFunction: IO_L7N_T1_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[16]}]

# PadFunction: IO_L8N_T1_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[17]}]

# PadFunction: IO_L11P_T1_SRCC_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[18]}]

# PadFunction: IO_L8P_T1_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[19]}]

# PadFunction: IO_L12N_T1_MRCC_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[20]}]

# PadFunction: IO_L10P_T1_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[21]}]

# PadFunction: IO_L11N_T1_SRCC_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[22]}]

# PadFunction: IO_L12P_T1_MRCC_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[23]}]

# PadFunction: IO_L2P_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[24]}]

# PadFunction: IO_L4N_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[25]}]

# PadFunction: IO_L1N_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[26]}]

# PadFunction: IO_L5N_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[27]}]

# PadFunction: IO_L4P_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[28]}]

# PadFunction: IO_L6P_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[29]}]

# PadFunction: IO_L1P_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[30]}]

# PadFunction: IO_L5P_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[31]}]

# PadFunction: IO_L1P_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[32]}]

# PadFunction: IO_L4N_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[33]}]

# PadFunction: IO_L5N_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[34]}]

# PadFunction: IO_L5P_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[35]}]

# PadFunction: IO_L2N_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[36]}]

# PadFunction: IO_L2P_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[37]}]

# PadFunction: IO_L1N_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[38]}]

# PadFunction: IO_L6P_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[39]}]

# PadFunction: IO_L7N_T1_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[40]}]

# PadFunction: IO_L10N_T1_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[41]}]

# PadFunction: IO_L11N_T1_SRCC_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[42]}]

# PadFunction: IO_L12P_T1_MRCC_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[43]}]

# PadFunction: IO_L7P_T1_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[44]}]

# PadFunction: IO_L10P_T1_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[45]}]

# PadFunction: IO_L8P_T1_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[46]}]

# PadFunction: IO_L8N_T1_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[47]}]

# PadFunction: IO_L17N_T2_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[48]}]

# PadFunction: IO_L13P_T2_MRCC_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[49]}]

# PadFunction: IO_L17P_T2_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[50]}]

# PadFunction: IO_L14P_T2_SRCC_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[51]}]

# PadFunction: IO_L13N_T2_MRCC_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[52]}]

# PadFunction: IO_L18N_T2_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[53]}]

# PadFunction: IO_L16P_T2_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[54]}]

# PadFunction: IO_L16N_T2_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[55]}]

# PadFunction: IO_L19P_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[56]}]

# PadFunction: IO_L22P_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[57]}]

# PadFunction: IO_L24P_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[58]}]

# PadFunction: IO_L23N_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[59]}]

# PadFunction: IO_L20N_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[60]}]

# PadFunction: IO_L22N_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[61]}]

# PadFunction: IO_L23P_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[62]}]

# PadFunction: IO_L20P_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[63]}]

# PadFunction: IO_L5N_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[13]}]

# PadFunction: IO_L2N_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[12]}]

# PadFunction: IO_L4P_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[11]}]

# PadFunction: IO_L5P_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[10]}]

# PadFunction: IO_L1P_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[9]}]

# PadFunction: IO_L10N_T1_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[8]}]

# PadFunction: IO_L6P_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[7]}]

# PadFunction: IO_L7P_T1_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[6]}]

# PadFunction: IO_L2P_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[5]}]

# PadFunction: IO_L4N_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[4]}]

# PadFunction: IO_L3N_T0_DQS_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[3]}]

# PadFunction: IO_L7N_T1_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[2]}]

# PadFunction: IO_L1N_T0_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[1]}]

# PadFunction: IO_L3P_T0_DQS_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[0]}]

# PadFunction: IO_L10P_T1_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[2]}]

# PadFunction: IO_L9N_T1_DQS_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[1]}]

# PadFunction: IO_L9P_T1_DQS_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[0]}]

# PadFunction: IO_L15N_T2_DQS_38 
set_property VCCAUX_IO HIGH [get_ports ddr3_ras_n]

# PadFunction: IO_L16P_T2_38 
set_property VCCAUX_IO HIGH [get_ports ddr3_cas_n]

# PadFunction: IO_L15P_T2_DQS_38 
set_property VCCAUX_IO HIGH [get_ports ddr3_we_n]

# PadFunction: IO_L14N_T2_SRCC_37 
set_property VCCAUX_IO HIGH [get_ports ddr3_reset_n]

# PadFunction: IO_L14P_T2_SRCC_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_cke[0]}]

# PadFunction: IO_L17N_T2_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_odt[0]}]

# PadFunction: IO_L16N_T2_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_cs_n[0]}]

# PadFunction: IO_L22N_T3_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[0]}]

# PadFunction: IO_L16P_T2_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[1]}]

# PadFunction: IO_L10N_T1_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[2]}]

# PadFunction: IO_L2N_T0_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[3]}]

# PadFunction: IO_L4P_T0_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[4]}]

# PadFunction: IO_L11P_T1_SRCC_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[5]}]

# PadFunction: IO_L18P_T2_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[6]}]

# PadFunction: IO_L24N_T3_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[7]}]

# PadFunction: IO_L12P_T1_MRCC_38 
set_property VCCAUX_IO DONTCARE [get_ports sys_clk_p]

# PadFunction: IO_L12N_T1_MRCC_38 

# PadFunction: IO_L13P_T2_MRCC_15 
set_property VCCAUX_IO DONTCARE [get_ports sys_rst]

# PadFunction: IO_L21P_T3_DQS_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[0]}]

# PadFunction: IO_L21N_T3_DQS_39 

# PadFunction: IO_L15P_T2_DQS_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[1]}]

# PadFunction: IO_L15N_T2_DQS_39 

# PadFunction: IO_L9P_T1_DQS_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[2]}]

# PadFunction: IO_L9N_T1_DQS_39 

# PadFunction: IO_L3P_T0_DQS_39 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[3]}]

# PadFunction: IO_L3N_T0_DQS_39 

# PadFunction: IO_L3P_T0_DQS_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[4]}]

# PadFunction: IO_L3N_T0_DQS_37 

# PadFunction: IO_L9P_T1_DQS_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[5]}]

# PadFunction: IO_L9N_T1_DQS_37 

# PadFunction: IO_L15P_T2_DQS_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[6]}]

# PadFunction: IO_L15N_T2_DQS_37 

# PadFunction: IO_L21P_T3_DQS_37 
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[7]}]

# PadFunction: IO_L21N_T3_DQS_37 

# PadFunction: IO_L13P_T2_MRCC_38 
set_property VCCAUX_IO HIGH [get_ports {ddr3_ck_p[0]}]

# PadFunction: IO_L13N_T2_MRCC_38 




## set_property LOC PHASER_IN_PHY_X1Y23 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y22 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y21 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]










current_instance dram/DDR3SDRAMController
set_multicycle_path -setup -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 6

set_multicycle_path -hold -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] 5

#set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r*}] #                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] #                    -setup 6

#set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r*}] #                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] #                    -hold 5

set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

set_multicycle_path -setup -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 2
set_multicycle_path -hold -start -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] 1

set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 5.000
set_max_delay -datapath_only -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] 5.000
#set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
#set_max_delay -from [get_cells -hier rstdiv0_sync_r1*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5

set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 5.000
#set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/*rst_r1*}] 20



